# Generated by Django 5.2 on 2025-05-07 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.profile",
            ),
        ),
    ]
