# Generated by Django 5.2 on 2025-05-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_item_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="user",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
