# Generated by Django 5.2 on 2025-05-16 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_delete_item"),
        ("items", "0002_alter_item_author"),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="profiles.profile"
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
